name: sfy deploy
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying ${{ github.ref }} to servicefoundry"
    - name: Install sfy
      run: pip install servicefoundry
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Deploy
      run: sfy deploy
      env:
        SERVICE_FOUNDRY_API_KEY: ${{ secrets.SERVICE_FOUNDRY_API_KEY }}